### ISSUE TITLE
Build EAST physics methods

### ISSUE THREAD

**Issue by yumouwei** [MIT-PSFC/disruption-py#347]
# Status

## efit.py

Function | Build | Validate | Note
--- | --- | --- | ---
get_efit_parameters | ✅ | ⚠️ | Fetched EFIT signals don't match the stored sql data for some disruptive shots.
get_pefit_parameters | ✅ | ✅ |

## physics.py

Function | Build | Validate | Note
--- | --- | --- | ---
get_time_until_disrupt | ✅ | ✅ | 
get_ip_parameters | ✅ | ✅ | 
get_v_loop | ✅ | ✅ | 
get_z_error | ✅ | ✅ | 
get_density_parameters | ✅ | ⚠️ |  `greenwald_fraction` affected by EFIT mismatch 
get_power | ✅ | ✅ | 
get_p_ohm | ✅ | ⚠️ |
(prad_bulk_xuv2014_2016) | ✅ | ✅ | Script missing in MATLAB branch
get_n_equal_1_data | ✅ | | Skip, implement at the end
(get_rmp_and_saddle_signals) | ✅ | ✅ | Included in `get_n_equal_1_data`
(calculate_rmp_saddle_coeff_matrix.m) | ✅ | ✅ | 
get_btor | ✅ | ✅ | Used by `get_n_equal_1_data`, `get_mirnov_std`, and `get_n1rms_n2rms`
get_efit_gaps | ✅ | ✅ |
get_pefit_gaps | ✅ | ✅ | 
get_kappa_area | ✅ | ⚠️ | `kappa_area` affected by EFIT mismatch
get_pkappa_area | ✅ | ✅ | 
~~get_pcs~~ | ➖ | ➖ | Broken into `get_pcs_parameters` and `get_pcs_powers`.
get_pcs_parameters | ✅ | ⚠️ | 
get_pcs_powers | ✅ | ✅ | `p_ecrh_rt`, `p_oh_rt`, `p_icrf_rt`, `rad_input_frac`, & `rad_loss_frac` weren't implemented in the source MATLAB script.
get_prad_peaking | ✅ | ✅ | 
get_mirnov_std | ✅ | ✅ | 
get_n1rms_n2rms | ✅ | ✅ | 
get_h98 | ✅ | ✅ | 

- (...): auxiliary functions
- ❌ : function can't run; bug(s).

## TODO prior to the validation stage
- [x] `get_n_equal_1_data`, `get_mirnov_std`, and `get_n1rms_n2rms` all use a similar method to compute `btor`. Consider making it into a standalone physics method.

## TODO at the validation stage

- [x] Verify MDS nodes
- [x] Verify units
- [ ] Check similar EFIT addresses (e.g. `\aout` vs `\aminor`)
- [ ] Check, add, or remove try-except logic.
- [ ] `interp1` extrapolation (e.g. in `get_power`)
- [x] Restructure repetitive code blocks to make things more efficient (e.g. get icrf power).
- [ ] Divide by 0 error (e.g. greenwald_fraction, rad_input_frac)
- [ ] `get_p_ohm`: replace 1.85 with r0 signal
- [x] `n1rms`, `n2rms`: database might have Mirnov_std stored in that column.
- [x] `n1rms_normalized`, `n2rms_normalized`: database has Mirnov_std_normalized stored in that column
- [x] `h98`: database has prad_peaking stored in that column
- [ ] Specify error types
- [x] `get_prad_peaking`: move all calibration factors to an util file.

## TODO after the validation stage

- [ ] Modify `get_heating_power()` to make it compatible with both `get_power()` and `get_pcs_power`.

## NOTE

- Pytest: Running `pytest -v tests/test_against_cache.py` raises `ValueError: could not broadcast input array from shape (750000,) into shape (1,)` error for every column, despite some of them (e.g. ip, ip_error) should have passed. For now I'm relying on using `python tests/test_against_cache.py` to check each column.

**Comment by yumouwei** [comment]
## Identified fails

Signal | Function | Error | Note
--- | --- | --- | ---
*all efit_cols* | get_efit_parameters | 53857: comparison failed |
area, <br /> aminor, <br /> chisq | get_efit_parameters | No column in SQL table |
*all efit_derivs* | get_efit_parameters | No column in SQL table |
*all pefit_cols* | get_pefit_parameters | 82440, 82445: %TREE-E-FOPENR, Tree not found. Tree: pefit_east
parea, <br /> pchisq, <br /> pconvergence | get_pefit_parameters | No column in SQL table |
ip_prog,<br /> dip_dt | get_ip_parameters | No column in SQL table | 
dipprog_dt | get_ip_parameters | 70022: comparison failed | 
btor | get_btor | 53857: TREE-E-NODATA: Tree: eng_tree, Node: \it | SQL table also has NULLs so it passes test
z_prog | get_z_error | No column in SQL table | 
zcur, <br /> z_error | get_z_error | 82440, 82440: %TREE-E-FOPENR, Tree not found. Nick: _efit_tree, Tree: efit_east | SQL table also has NULLs so it passes test
zcur_lmsz, <br /> z_error_lmsz, <br /> zcur_lmsz_normalized, <br /> z_error_lmsz_normalized | get_z_error | 82440: comparison failed; 82440, 82445: %TREE-E-FOPENR, Tree not found. Nick: _efit_tree, Tree: efit_east | Fresh: all NaN, Cache: data
n_e, <br /> greenwald_fraction | get_density_parameters | 55555: comparison failed; a couple shots have Tree not found error | Fresh: NaN
dn_dt | get_efit_parameters | No column in SQL table |
*all* | get_power | | Bug in function
p_rad | get_power |  | Incomplete
kappa_area | get_kappa_area | 53857: comparison failed; a couple shots have Tree not found error | 53857: Fresh has more time points with data than Cache
pkappa_area | get_pkappa_area | all 6 test shots: no column in SQL table | 82440, 82440: same no pefit_east tree error
ip_error_rt | get_pcs_parameters | 55555: Fresh: NaN |
q95_rt | get_pcs_parameters | all 6 test shots: Cache: NaN | Tested using 74646 (has Cache data): %TREE-W-NNF, Node not found. Tree: pcs_east, Node: \pfsbetap
beta_p_rt, <br /> li_rt, <br /> wmhd_rt | get_pcs_parameters | 55555: Fresh: NaN | %TREE-W-NNF, Node not found. Tree: pcs_east, Node: \pfsbetap
p_lh_rt, p_nbi_rt | get_pcs_power | 55555: Fresh: NaN | %TREE-E-FOPENR, Tree not found. Tree: pefitrt_east
prad_peaking | get_prad_peaking | | Bug
mirnov_std, <br /> mirnov_std_normalized | get_mirnov_std | | %TREE-W-NNF, Node not found. Tree: east, Node: \Mirnov_sensorcmp1t
n1rms, <br /> n2rms, <br /> n1rms_normalized, <br /> n2rms_normalized | get_n1rms_n2rms | | Bug; n1rms_normalized & n2rms_normalized columns have Mirnov_std & Mirnov_std_normalized data 
h98 | get_h98 | comparison failed | SQL table has prad_peaking in h98 column

**Comment by lajz** [comment]
It would be cool to hear about the highest points of friction that you have in this process, with the idea of building tooling to support it. Eg. we should be able to easily sweep shotlists and record error types
